### ISSUE TITLE
feat: How to read files in the current requested context...

### ISSUE THREAD

**Issue by ammarjavedofficial** [VeryGoodOpenSource/dart_frog#394] opened 2022-10-19 18:42 UTC
If we try to send a file such as image file in the request then how to get it's name in the current requested context

**Comment by felangel** [comment] 2022-10-20 14:57
Hi @ammarjavedofficial 👋 
Thanks for opening an issue!

This is a duplicate of #296 and in the meantime I recommend taking a look at https://pub.dev/packages/shelf_multipart for inspiration.

**Closed by felangel** 2022-10-20 14:57 UTC

**Comment by ammarjavedofficial** [comment] 2022-10-22 17:33
Create APIs with Dart Frog Backend Server For Flutter / Dart

[https://ammarjaved.com/create-apis-with-dart-frog-backend-server-for-dart-flutter](https://ammarjaved.com/create-apis-with-dart-frog-backend-server-for-dart-flutter)
