### ISSUE TITLE
feat: database support and .env

### ISSUE THREAD

**Issue by SPiercer** [VeryGoodOpenSource/dart_frog#302] opened 2022-08-29 04:44 UTC
**Description**

Adding .env configurations in order to add databases support (i.e mysql or postgres) to the dart_frog server
whereas once you have the .env values of for instance mysql address and credentials it will add it to the server initialization
 
**Requirements**

- [ ] adding out of the box .env support
- [ ] adding databases support

**P.S**

i'm glad to help by any means if anyone is ready to take this contribution outside of the vgv team
i've been working on a similar project before called Palace but it's archived now since we went to uni and decided to come back later.

**Comment by aaltynbek** [comment] 2022-08-31 15:51
@SPiercer Hello there is package https://pub.dev/packages/mysql_client to work with mysql DB, it's good for starting, but .env will be good for dart_frog

**Comment by SPiercer** [comment] 2022-09-01 11:24
> @SPiercer Hello there is package https://pub.dev/packages/mysql_client to work with mysql DB, it's good for starting, but .env will be good for dart_frog

@aaltynbek man, there is not way i can initialize the mysql client on the server because i have no access to edit server.dart basically in dev mode

**Comment by ushieru** [comment] 2022-09-10 01:42
@SPiercer You can create a custom entrypoint, simply create a main.dart file at the root of your Dart Frog project. The main.dart file must expose a top-level run method.

[Official Doc](https://dartfrog.vgv.dev/docs/advanced/custom_entrypoint#creating-a-custom-entrypoint-)

```dart
import 'dart:io';

import 'package:dart_frog/dart_frog.dart';

Future<HttpServer> run(Handler handler, InternetAddress ip, int port) {
  // 1. Execute any custom code prior to starting the server...

  // 2. Use the provided `handler`, `ip`, and `port` to create a custom `HttpServer`.
  // Or use the Dart Frog serve method to do that for you.
  return serve(handler, ip, port);
}
```

**Comment by mgesmundo** [comment] 2022-10-22 11:35
I use a custom entry point to set some values, but the problem is that it could be useful to set some env variables on dev mode using the `dart_from` CLI like this example:

```bash
dart_frog --define=SOME_TOKEN=1234 dev
```

In this way it is possible to compile and use the server for production:

```bash
dart_frog build
dart compile exe build/bin/server.dart -o build/bin/server
dart run --define= SOME_TOKEN =1234 build/bin/server
```

Actually I can't figured out some workaround to set an env variable using `dart_frog` CLI.
There is one?
Thank you.

**Comment by GabrielRozendo** [comment] 2022-11-22 12:01
The package [dotenv](https://pub.dev/packages/dotenv) solves this issue for me very well.
In my dev env, I'm using a .env file and in the prd server, the env var from machine.

I dont think it is a issue that Dart Frog should address, as you can do it by yourself, even reading from a file from Dart or  from [yaml files](https://pub.dev/packages/yaml) as I've seen other dart server's project doing.

**Comment by mgesmundo** [comment] 2022-11-23 11:35
Yes of course: to read a yaml file is the easy solution (I've also applied it), but if you want to make more safe the environment, you do not save password or other sensitive data in any local file.

**Comment by GabrielRozendo** [comment] 2022-11-23 20:17
> Yes of course: to read a yaml file is the easy solution (I've also applied it), but if you want to make more safe the environment, you do not save password or other sensitive data in any local file.

for that reason I use dotenv.
In my machine, I have a .env file with the password in open text, and (without change any line of code), in prd server, it'll use the env from server (no file anymore)

**Comment by AseemWangoo** [comment] 2023-01-04 07:55
I'm trying to use the `envied` package for storing keys. But whenever I run the 

```
dart_frog dev
```

I always get this error

<img width="772" alt="image" src="https://user-images.githubusercontent.com/16626254/210507977-50fae1ed-70c6-4686-9799-820eb9cd23a0.png">

This is my project structure:
<img width="249" alt="image" src="https://user-images.githubusercontent.com/16626254/210508234-4b23a33d-bdd6-415b-a750-806e1264607b.png">

and this is the package that has the `package envied` installed

<img width="257" alt="image" src="https://user-images.githubusercontent.com/16626254/210508195-de6b428d-3e41-4d1f-b901-74c3a20900c2.png">

**Comment by wolfenrain** [comment] 2023-04-18 18:06
I am closing this issue as this is outside of the scope of Dart Frog, both setting up env and database are really specific to how a user wants to do it and people have already given nice solutions in the issue thread.

We can in the near future maybe create some documentation/tutorials on how to set it up, but that will be it's own issue.

**Closed by wolfenrain** 2023-04-18 18:06 UTC
