### ISSUE TITLE
fix: .gitignore carries over when building from the dart_frog dockerfile

### ISSUE THREAD

**Issue by Tameflame** [VeryGoodOpenSource/dart_frog#589] opened 2023-03-29 12:42 UTC
I used the envied package to handle environment variables, and naturally my .env file was in my .gitignore.

However when trying to build the container on google cloud run, building kept failling. And turns out I had to remove the .env file from my gitignore in the build directory and only then it would build properly.

I don't know whether this is an issue here or with docker or intended, but it gets annoying having to uncomment out manually the ignored files in build/.gitignore.

**Comment by wolfenrain** [comment] 2023-04-05 13:23
Docker does not use the `.gitignore` and neither does Dart Frog, maybe something in Google Cloud Run is using it to ignore files?

I have tried it locally and I am able to build a docker image that uses files that are in my `.gitignore`. If you can provide a reproduceable example for me to look at, that would be super sweet!

**Comment by wolfenrain** [comment] 2023-04-24 17:39
Closing this as we are not able to reproduceable the issue, as mentioned above it seems to work as intended

**Closed by wolfenrain** 2023-04-24 17:39 UTC
Labels: bug, waiting for response
