### ISSUE TITLE
fix: shelf_web_socket

### ISSUE THREAD

**Issue by MattiaPispisa** [VeryGoodOpenSource/dart_frog#463] opened 2023-01-03 09:36 UTC
**Description**

`dart_frog_websocket` requires  `shelf_web_socket: ^1.0.0` but with `shelf_web_socket: 1.0.2` is not working:

ERROR - 2023-01-03 10:31:57.229745
Asynchronous error
NoSuchMethodError: Closure call with mismatched arguments: function 'onRequest.<anonymous closure>'
Receiver: Closure: (WebSocketChannel, String?) => void
Tried calling: onRequest.<anonymous closure>(Instance of 'WebSocketChannel')
Found: onRequest.<anonymous closure>(WebSocketChannel, String?) => void
dart:core                                                   _objectNoSuchMethod
package:shelf_web_socket/shelf_web_socket.dart 49:55        webSocketHandler.<fn>
package:shelf_web_socket/src/web_socket_handler.dart 81:20  WebSocketHandler.handle.<fn>

**Steps To Reproduce**

Setup `dart_frog` as global: `dart pub global activate dart_frog_cli` with  `shelf_web_socket: 1.0.2` in `pub-cache/bin`

**Expected Behavior**
set shelf_web_socket: ^1.0.3 in `dart_frog_websocket`

**Comment by felangel** [comment] 2023-01-03 15:44
Hi @MattiaPispisa 👋 
Thanks for opening an issue!

It looks like shelf_web_socket 1.0.3 requires Dart >=2.17 so I'm guessing you need to upgrade your version of Dart. I was not able to reproduce the issue using the latest stable version of Dart. Let me know if that helps 👍

**Comment by MattiaPispisa** [comment] 2023-01-03 17:04
Thanks for the feedback. 
The problem is not shelf_web_socket 1.0.3 but shelf_web_socket 1.0.2 ( it is resolved with shelf_web_socket 1.0.3). 
Since dart_frog_websocket requires shelf_web_socket ^1.0.0, shelf_web_socket 1.0.2 is a valid version but this will lead to a run time exception.

**Comment by felangel** [comment] 2023-01-03 17:18
Thanks for clarifying, just merged #464 to address this 👍

**Closed** 2023-01-03 17:18 UTC
Labels: bug, question, waiting for response
