### ISSUE TITLE
feat: `dart_frog dev` should be able to `--write-service-info`

### ISSUE THREAD

**Issue by Luckey-Elijah** [VeryGoodOpenSource/dart_frog#406] opened 2022-11-01 19:54 UTC
**Description**

When executing `dart` with `--enable-vm-service` you the ability to write a the "VM service info" file that holds a reference to the VM service URI. It's the URI from the `dart_frog dev` command:

```
The Dart VM service is listening on http://127.0.0.1:8181/hbDoUv07zvg=/
```

The file contents are JSON.
```json
{"uri":"http://127.0.0.1:8181/hbDoUv07zvg=/"}
```

This file enables VS Code (and potentially Android Studio) users to connect the debugger automatically through a launch config.  I'd like to see an option for `dart_frog dev` to write this file for debuggers to attach to.

## Example 
If `dart_frog dev` wrote the VM info file to `.dart_frog/vm-service-info.json`, (and using a `hello_world` project, like the `examples/`)

#### `.vscode/tasks.json`
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "run hello world example",
      "command": "dart_frog",
      "args": ["dev", "--write-service-info"],
      "problemMatcher": [],
      "isBackground": true,
    }
  ]
}
```
#### `.vscode/launch.json`
```jsonc
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Then Attach dart_frog to debugger",
      "request": "attach",
      "type": "dart",
      "preLaunchTask": "run hello world example",

      // path to the "vm-service-info.json"
      "vmServiceInfoFile": "${workspaceFolder}/.dart_frog/vm-service-info.json",
      "deleteServiceInfoFile": true
    }
  ]
}
```

**Requirements**

- [ ] add `--write-service-info` flag to `dart_frog dev`
- [ ] writes `vm-service-info.json` to `dart_frog`

**Additional Context**

VSCode extension demonstrate support
https://github.com/Dart-Code/Dart-Code/issues/2424

Related `dart_frog` Issues:
 - #286

**Comment by wolfenrain** [comment] 2022-11-21 19:22
Since this is a duplicate of #286 where we are going to implement this, we will be closing this.

But for anyone looking to quickly get it up and running for themselves the above will work! Thank you for looking into this <3

**Closed** 2022-11-21 19:22 UTC
Labels: enhancement
