### ISSUE TITLE
fix: Error on running dart_frog dev --port =3005

### ISSUE THREAD

**Issue by nimr77** [VeryGoodOpenSource/dart_frog#346] opened 2022-09-28 13:22 UTC
**Description**

I'm developing a web server to get Tiles for map, And I picked dart frog as my programming language to do so, I launched the test and it worked and a got the hello world message, yet after edit I'm getting issues on running the program again 

```.dart_frog/server.dart:34:41: Error: Undefined name 'onRequest'.
    ..all('/service', api_tiles_service.onRequest)..all('/model', api_tiles_model.onRequest)..all('/', api_tiles_index.onRequest);
```

I have no idea why 
what I have created is 
```
analysis_options.yaml  public  pubspec.lock  pubspec.yaml  README.md  routes  test
```
and inside the public folder
```
other  tiles
```
the other is empty and the tiles folder has sub folders following x/y/z.png, which x,y and z are number 

and in my routes I have this 
```
api  index.dart
```
API folder has 
```
tiles
```
```
index.dart  model.dart  service.dart
```
my code of index.dart 
```
import 'package:dart_frog/dart_frog.dart';

Response onRequest(RequestContext context) {
  return Response(body: 'Welcome to Dart Frog!');
}

```
and my service.dart

```
import 'dart:io';

import 'model.dart';

class TileService {
  String locationOnStorage = './public';

  Future<List<Tile>> getTiles({
    required String z,
    required String x,
    required String y,
  }) async {
    final tiles = <Tile>[];

    return tiles;
  }

  Future<Tile?> getTile({
    required String z,
    required String x,
    required String y,
  }) async {
    final path = '$locationOnStorage/$z/$x/$y.png';
    final file = File(path);
    if (file.existsSync()) {
      return Tile(
        x: int.parse(x),
        z: int.parse(z),
        y: int.parse(y),
        path: path,
        name: file.path.split('/').last,
      );
    }
    return null;
  }
}

```
and the model.dart
```
class Tile {
  Tile({
    required this.x,
    required this.z,
    required this.y,
    required this.path,
    required this.name,
  });

  int x;
  int z;
  int y;
  String path;
  String name;
}
```

**Comment by nimr77** [comment] 2022-09-28 13:29
After putting the model.dart and service.dart out of the routes it worked

**Comment by felangel** [comment] 2022-09-28 13:53
Hi @nimr77 👋
Thanks for opening an issue!

Can we close this since it sounds like you were able to resolve the issue? If not can you please provide a link to a minimal reproduction sample with steps to reproduce the issue you’re facing? Thanks!

**Closed** 2022-09-28 13:55 UTC
Labels: question, waiting for response
