### ISSUE TITLE
docs: Get caller IP

### ISSUE THREAD

**Issue by rsc1975** [VeryGoodOpenSource/dart_frog#262] opened 2022-08-14 17:14 UTC
**Description**

How can I get the caller's remote IP from Request ?

**Comment by felangel** [comment] 2022-08-14 19:59
Hi @rsc1975 👋
Thanks for opening an issue!

This is a duplicate of #203 and should be addressed shortly 👍

**Closed** 2022-08-14 19:59 UTC
Labels: duplicate
