### ISSUE TITLE
fix: windows route generation

### ISSUE THREAD

**Issue by dhrubrawat66** [VeryGoodOpenSource/dart_frog#130] opened 2022-07-01 13:05 UTC
**Steps To Reproduce**

**Expected Behavior**

**![final](https://user-images.githubusercontent.com/85351405/176900099-95928e8e-e533-44b6-82d9-8fde12307618.png)**

**Additional Context**

**Comment by dhrubrawat66** [comment] 2022-07-01 13:17
this is happened in the window operating system. if i stop and restart the server then also appear the bug like above.

**Comment by felangel** [comment] 2022-07-01 14:23
Hi @dhrubrawat66 👋
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample? Thanks!

**Comment by felangel** [comment] 2022-07-07 16:22
Closing for now since there aren't any actionable next steps. Feel free to provide a minimal reproduction sample and I'm happy to take a closer look 👍

**Closed by felangel** 2022-07-07 16:22 UTC
Labels: question, waiting for response
