### ISSUE TITLE
canot start my project

### ISSUE THREAD

**Issue by bobwatcherx** [VeryGoodOpenSource/dart_frog#396] opened 2022-10-25 04:48 UTC
i have problem . i use root , but get message error like this . 
MY DART VERSION:
📎
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "linux_x64"

root@ubuntux-Lenovo-V145-14AST:/home/ubuntux/belajar/dartapp/proj# dart_frog dev
```
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
✓ Running on http://localhost:8080 (5.5s)
Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
```

**Comment by felangel** [comment] 2022-10-25 20:24
Hi @bobwatcherx 👋 
Thanks for opening an issue!

It looks like you are running `dart_frog dev` as a root user which is not recommended. This is working as expected and is consistent with how the dart/flutter tooling works.

Closing for now since there are no actionable next steps but feel free to comment with any follow-up questions and I'm happy to continue the conversation 👍

**Closed by felangel** 2022-10-25 20:24 UTC
Labels: question

**Comment by bobwatcherx** [comment] 2022-10-29 01:01
I no longer use root

but there is a problem running it

ubuntux@ubuntux-Lenovo-V145-14AST:~/belajar/dartapp/dartfrog$ dart_frog dev
⠏ Serving... (0.7s)Unable to execute hook: pre_gen.dart.
Error: Type 'RouteConfiguration' not found.
  RouteConfiguration configuration,

**Comment by felangel** [comment] 2022-10-29 01:02
> I no longer use root
> 
> but there is a problem running it
> 
> ubuntux@ubuntux-Lenovo-V145-14AST:~/belajar/dartapp/dartfrog$ dart_frog dev ⠏ Serving... (0.7s)Unable to execute hook: pre_gen.dart. Error: Type 'RouteConfiguration' not found. RouteConfiguration configuration,

Can you provide reproduction steps? How did you install Dart?

**Comment by bobwatcherx** [comment] 2022-10-29 02:04
i installed darts for flutter
with snap on ubuntu
`snap install flutter --classic`
```
ubuntux@ubuntux-Lenovo-V145-14AST:~/belajar/dartapp/dartfrog$ which dart
sh: 0: getcwd() failed: No such file or directory
/snap/bin/dart
```
**info**
dart_frog version :
0.2.2
Dart SDK version: 2.18.2 (stable)
**my pubspec.yaml**
```
name: dartfrog
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.2.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
```

**Comment by felangel** [comment] 2022-10-29 02:28
> i installed darts for flutter with snap on ubuntu **(Ubuntu 22.04 LTS )** `snap install flutter --classic`
> 
> ```
> ubuntux@ubuntux-Lenovo-V145-14AST:~/belajar/dartapp/dartfrog$ which dart
> sh: 0: getcwd() failed: No such file or directory
> /snap/bin/dart
> ```
> 
> **info** dart_frog version : 0.2.2 Dart SDK version: 2.18.2 (stable) **my pubspec.yaml**
> 
> ```
> name: dartfrog
> description: An new Dart Frog application
> version: 1.0.0+1
> publish_to: none
> 
> environment:
>   sdk: ">=2.18.0 <3.0.0"
> 
> dependencies:
>   dart_frog: ^0.2.0
> 
> dev_dependencies:
>   mocktail: ^0.3.0
>   test: ^1.19.2
>   very_good_analysis: ^3.1.0
> ```

I’ll try to see if I can reproduce. Can you verify whether you can run other dart_frog commands like dart_frog create or dart_frog build? Also is this only a problem when you don’t run as root? Thanks!
